travis.yml para CD 9

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -31,7 +31,7 @@ deploy:
     echo "Starting deployment"
     echo "FTP_SERVER: $FTP_SERVER"
     echo "FTP_USERNAME: $FTP_USERNAME"
-    lftp -e "set ftp:ssl-verify-certificate no; mirror -R ./public /domains/luishs.com/public_html/travis2; quit" -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER || { echo "Deployment failed"; exit 1; }
+    lftp -e "set ftp:ssl-force false; mirror -R ./public /domains/luishs.com/public_html/travis2; quit" -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER || { echo "Deployment failed"; exit 1; }
     echo "Deployment finished"
   skip_cleanup: true
   on:
